import type { Metadata } from 'next';
import './globals.css';

// CDS imports
import '@coinbase/cds-icons/fonts/web/icon-font.css';
import '@coinbase/cds-web/globalStyles';
import '@coinbase/cds-web/defaultFontStyles';
import { CDSThemeProvider } from '../providers/CDSThemeProvider';
import { CDSMediaQueryProvider } from '../providers/CDSMediaQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CDSMediaQueryProvider>
          <CDSThemeProvider>{children}</CDSThemeProvider>
        </CDSMediaQueryProvider>
      </body>
    </html>
  );
}
